version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: erp_budget_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: erp_budget_tracker
    volumes:
      - mongodb_data:/data/db
    networks:
      - erp_network

  backend:
    build: .
    container_name: erp_budget_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/erp_budget_tracker?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_for_production
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your_email@gmail.com
      EMAIL_PASS: your_app_password
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - erp_network

volumes:
  mongodb_data:

networks:
  erp_network:
    driver: bridge